#pragma once
//#define __MAIN_MAIN__
//#define __MAIN_CAMERA_CPP__
//#define __MAIN_PARTICLES_CPP__
//#define __MAIN_PARTICLES_TERRAIN_CPP__
//#define __MAIN_SHADOW__
//#define __MAIN_TERRAIN_BITMAP_DOUBLECOATED_CPP__
//#define __MAIN_TERRAIN_BITMAP_DOUBLECOATED_INDEXED_CPP__
//#define __MAIN_TERRAIN_BITMAP_DOUBLE_COATED_VINEET_CPP__
//#define __MAIN_TERRAIN_BITMAP_DOUBLE_COATED_FRAME_BUFFERS__
//#define __MAIN_TERRAIN_BITMAP_SHADERS_CPP__
//#define __MAIN_TERRAIN_TESSELLATED_CPP__
//#define __MAIN_TESSELLATION_CPP__
//#define __MAIN_TRIANGLE_LIB__
//#define __MAIN_SPHERE_DODECAHEDRON_CPP__

//// Dynamit stays apart
//#define __DYNAMIT_CPP__
//#define __DYNAMIT_DRAW0_CPP__
//#define __DYNAMIT_DRAW_STRIDED_CPP__
//#define __DYNAMIT_ANIMATE_CPP__
//#define __DYNAMIT_NORMALS_AND_COLORS_2PROGS_CPP__
//#define __DYNAMIT_TRIANGLE_FAN_CPP__
//#define __DYNAMIT_TRIANGLE_FAN_PRIMITIVES_CPP__
//#define __DYNAMIT_CONE1_ANIMATE1_CPP__
//#define __DYNAMIT_CONE1_ANIMATE1_CALC_CPP__
//#define __DYNAMIT_CONE1_ANIMATE2_CPP__
//#define __DYNAMIT_CONE1_GEOMETRY1_CPP__
//#define __DYNAMIT_CONE1_HEART_GEOMETRY1_CPP__
//#define __DYNAMIT_CONE1_HEART_GEOMETRY2_CPP__
//#define __DYNAMIT_SPHERE_DODECAHEDRON_CPP__
//#define __DYNAMIT_SPHERE_DODECAHEDRON_TEXTURED_CPP__

//These use shape builders
//#define __DYNAMIT_CONE1_HEART_GEOMETRY2_CALC_CPP__
//#define __DYNAMIT_CONE1_HEART_GEOMETRY2_CALC_BUILDER_CPP__
//#define __DYNAMIT_CONE_GEOMETRY_CALC_CPP__
#define __DYNAMIT_CYLINDER_GEOMETRY_CALC_CPP__ 