//! Visual demo: Render polar shapes with OpenGL
//!
//! Creates a window and renders a rotating shape generated by PolarBuilder.

use std::ffi::CString;
use std::num::NonZeroU32;
use std::f32::consts::PI;

use glow::HasContext;
use glutin::config::ConfigTemplateBuilder;
use glutin::context::{ContextApi, ContextAttributesBuilder, Version};
use glutin::display::GetGlDisplay;
use glutin::prelude::*;
use glutin::surface::SwapInterval;
use glutin_winit::{DisplayBuilder, GlWindow};
use raw_window_handle::HasRawWindowHandle;
use winit::event::{Event, KeyEvent, WindowEvent};
use winit::event_loop::EventLoop;
use winit::keyboard::{Key, NamedKey};
use winit::window::WindowBuilder;

use dynamit_rs::{PolarBuilder, perspective, look_at, multiply_mat4, rotation_y_mat4, rotation_x_mat4};

const VERTEX_SHADER: &str = r#"
#version 330 core
layout(location = 0) in vec3 aPos;
layout(location = 1) in vec3 aNormal;
layout(location = 2) in vec4 aColor;

uniform mat4 uMVP;
uniform mat4 uModel;

out vec3 vNormal;
out vec4 vColor;
out vec3 vFragPos;

void main() {
    gl_Position = uMVP * vec4(aPos, 1.0);
    vFragPos = vec3(uModel * vec4(aPos, 1.0));
    vNormal = mat3(transpose(inverse(uModel))) * aNormal;
    vColor = aColor;
}
"#;

const FRAGMENT_SHADER: &str = r#"
#version 330 core
in vec3 vNormal;
in vec4 vColor;
in vec3 vFragPos;

out vec4 FragColor;

void main() {
    vec3 lightDir = normalize(vec3(1.0, 1.0, 1.0));
    vec3 norm = normalize(vNormal);

    float ambient = 0.3;
    float diff = max(dot(norm, lightDir), 0.0);
    float lighting = ambient + diff * 0.7;

    FragColor = vec4(vColor.rgb * lighting, vColor.a);
}
"#;

fn main() {
    let event_loop = EventLoop::new().unwrap();

    let window_builder = WindowBuilder::new()
        .with_title("Dynamit RS - Visual Demo")
        .with_inner_size(winit::dpi::LogicalSize::new(800, 600));

    let template = ConfigTemplateBuilder::new().with_alpha_size(8);

    let display_builder = DisplayBuilder::new().with_window_builder(Some(window_builder));

    let (window, gl_config) = display_builder
        .build(&event_loop, template, |configs| {
            configs
                .reduce(|accum, config| {
                    if config.num_samples() > accum.num_samples() {
                        config
                    } else {
                        accum
                    }
                })
                .unwrap()
        })
        .unwrap();

    let window = window.unwrap();
    let raw_window_handle = window.raw_window_handle();

    let gl_display = gl_config.display();

    let context_attributes = ContextAttributesBuilder::new()
        .with_context_api(ContextApi::OpenGl(Some(Version::new(3, 3))))
        .build(Some(raw_window_handle));

    let gl_context = unsafe {
        gl_display
            .create_context(&gl_config, &context_attributes)
            .unwrap()
    };

    let attrs = window.build_surface_attributes(<_>::default());
    let gl_surface = unsafe {
        gl_config
            .display()
            .create_window_surface(&gl_config, &attrs)
            .unwrap()
    };

    let gl_context = gl_context.make_current(&gl_surface).unwrap();

    let gl = unsafe {
        glow::Context::from_loader_function(|s| {
            let s = CString::new(s).unwrap();
            gl_display.get_proc_address(&s) as *const _
        })
    };

    gl_surface
        .set_swap_interval(&gl_context, SwapInterval::Wait(NonZeroU32::new(1).unwrap()))
        .ok();

    // Compile shaders
    let program = unsafe {
        let vertex_shader = gl.create_shader(glow::VERTEX_SHADER).unwrap();
        gl.shader_source(vertex_shader, VERTEX_SHADER);
        gl.compile_shader(vertex_shader);
        if !gl.get_shader_compile_status(vertex_shader) {
            panic!("Vertex shader error: {}", gl.get_shader_info_log(vertex_shader));
        }

        let fragment_shader = gl.create_shader(glow::FRAGMENT_SHADER).unwrap();
        gl.shader_source(fragment_shader, FRAGMENT_SHADER);
        gl.compile_shader(fragment_shader);
        if !gl.get_shader_compile_status(fragment_shader) {
            panic!("Fragment shader error: {}", gl.get_shader_info_log(fragment_shader));
        }

        let program = gl.create_program().unwrap();
        gl.attach_shader(program, vertex_shader);
        gl.attach_shader(program, fragment_shader);
        gl.link_program(program);
        if !gl.get_program_link_status(program) {
            panic!("Program link error: {}", gl.get_program_info_log(program));
        }

        gl.delete_shader(vertex_shader);
        gl.delete_shader(fragment_shader);

        program
    };

    // Generate shape
    let mut verts = Vec::new();
    let mut norms = Vec::new();
    let mut colors = Vec::new();
    let mut indices = Vec::new();

    PolarBuilder::new()
        .formula("1 + 0.3*sin(5*theta)")
        .sectors(48)
        .double_coated(true)
        .color_outer(1.0, 0.6, 0.1, 1.0)  // Orange
        .color_inner(0.2, 0.4, 0.8, 1.0)  // Blue
        .build_cone_indexed_with_color(&mut verts, &mut norms, &mut colors, &mut indices)
        .unwrap();

    println!("Generated {} vertices, {} indices", verts.len() / 3, indices.len());

    // Create VAO/VBO
    let (vao, _vbo_pos, _vbo_norm, _vbo_color, _ebo) = unsafe {
        let vao = gl.create_vertex_array().unwrap();
        gl.bind_vertex_array(Some(vao));

        // Position buffer
        let vbo_pos = gl.create_buffer().unwrap();
        gl.bind_buffer(glow::ARRAY_BUFFER, Some(vbo_pos));
        gl.buffer_data_u8_slice(
            glow::ARRAY_BUFFER,
            bytemuck::cast_slice(&verts),
            glow::STATIC_DRAW,
        );
        gl.vertex_attrib_pointer_f32(0, 3, glow::FLOAT, false, 0, 0);
        gl.enable_vertex_attrib_array(0);

        // Normal buffer
        let vbo_norm = gl.create_buffer().unwrap();
        gl.bind_buffer(glow::ARRAY_BUFFER, Some(vbo_norm));
        gl.buffer_data_u8_slice(
            glow::ARRAY_BUFFER,
            bytemuck::cast_slice(&norms),
            glow::STATIC_DRAW,
        );
        gl.vertex_attrib_pointer_f32(1, 3, glow::FLOAT, false, 0, 0);
        gl.enable_vertex_attrib_array(1);

        // Color buffer
        let vbo_color = gl.create_buffer().unwrap();
        gl.bind_buffer(glow::ARRAY_BUFFER, Some(vbo_color));
        gl.buffer_data_u8_slice(
            glow::ARRAY_BUFFER,
            bytemuck::cast_slice(&colors),
            glow::STATIC_DRAW,
        );
        gl.vertex_attrib_pointer_f32(2, 4, glow::FLOAT, false, 0, 0);
        gl.enable_vertex_attrib_array(2);

        // Index buffer
        let ebo = gl.create_buffer().unwrap();
        gl.bind_buffer(glow::ELEMENT_ARRAY_BUFFER, Some(ebo));
        gl.buffer_data_u8_slice(
            glow::ELEMENT_ARRAY_BUFFER,
            bytemuck::cast_slice(&indices),
            glow::STATIC_DRAW,
        );

        gl.bind_vertex_array(None);

        (vao, vbo_pos, vbo_norm, vbo_color, ebo)
    };

    let mvp_loc = unsafe { gl.get_uniform_location(program, "uMVP") };
    let model_loc = unsafe { gl.get_uniform_location(program, "uModel") };

    let mut angle = 0.0f32;
    let index_count = indices.len() as i32;

    unsafe {
        gl.enable(glow::DEPTH_TEST);
        gl.clear_color(0.1, 0.1, 0.15, 1.0);
    }

    event_loop
        .run(move |event, elwt| {
            match event {
                Event::WindowEvent { event, .. } => match event {
                    WindowEvent::CloseRequested => elwt.exit(),
                    WindowEvent::KeyboardInput {
                        event: KeyEvent { logical_key: Key::Named(NamedKey::Escape), .. },
                        ..
                    } => elwt.exit(),
                    WindowEvent::Resized(size) => {
                        if size.width != 0 && size.height != 0 {
                            gl_surface.resize(
                                &gl_context,
                                NonZeroU32::new(size.width).unwrap(),
                                NonZeroU32::new(size.height).unwrap(),
                            );
                            unsafe {
                                gl.viewport(0, 0, size.width as i32, size.height as i32);
                            }
                        }
                    }
                    WindowEvent::RedrawRequested => {
                        angle += 0.01;

                        let size = window.inner_size();
                        let aspect = size.width as f32 / size.height as f32;

                        // Build MVP matrix
                        let projection = perspective(45.0 * PI / 180.0, aspect, 0.1, 100.0);
                        let view = look_at(
                            [0.0, 1.5, 3.0],
                            [0.0, 0.3, 0.0],
                            [0.0, 1.0, 0.0],
                        );
                        let model = multiply_mat4(
                            &rotation_y_mat4(angle),
                            &rotation_x_mat4(-0.3),
                        );
                        let mvp = multiply_mat4(&projection, &multiply_mat4(&view, &model));

                        unsafe {
                            gl.clear(glow::COLOR_BUFFER_BIT | glow::DEPTH_BUFFER_BIT);

                            gl.use_program(Some(program));
                            gl.uniform_matrix_4_f32_slice(mvp_loc.as_ref(), false, &mvp);
                            gl.uniform_matrix_4_f32_slice(model_loc.as_ref(), false, &model);

                            gl.bind_vertex_array(Some(vao));
                            gl.draw_elements(glow::TRIANGLES, index_count, glow::UNSIGNED_INT, 0);
                            gl.bind_vertex_array(None);
                        }

                        gl_surface.swap_buffers(&gl_context).unwrap();
                        window.request_redraw();
                    }
                    _ => {}
                },
                _ => {}
            }
        })
        .unwrap();
}
